### ISSUE TITLE
help -- Identifier expected

### ISSUE THREAD

**Issue by bycs06** [ClosedXML/ClosedXML#275]
i have excel file that has two worksheet named ws1 and ws2. in ws1  there is a cell contain formula related to ws2. when i want to get value from the cell in ws1 program gives error
note: excel file is attached.

[dene.xlsx](https://github.com/ClosedXML/ClosedXML/files/928673/dene.xlsx)

```
System.Exception was unhandled
  HResult=-2146233088
  Message=Identifier expected.
  Source=ClosedXML
  StackTrace:
       konum: ClosedXML.Excel.CalcEngine.CalcEngine.GetToken() C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs içinde: satır 589
       konum: ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs içinde: satır 81
       konum: ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs içinde: satır 47
       konum: ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs içinde: satır 108
       konum: ClosedXML.Excel.XLCell.get_Value() C:\Projects\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs içinde: satır 407
       konum: tasarim.Form2.button1_Click(Object sender, EventArgs e) D:\Users\....\Documents\Visual Studio 2015\Projects\tasarim\tasarim\Form2.cs içinde: satır 316
       konum: System.Windows.Forms.Control.OnClick(EventArgs e)
       konum: System.Windows.Forms.Button.OnClick(EventArgs e)
       konum: System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       konum: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       konum: System.Windows.Forms.Control.WndProc(Message& m)
       konum: System.Windows.Forms.ButtonBase.WndProc(Message& m)
       konum: System.Windows.Forms.Button.WndProc(Message& m)
       konum: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       konum: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       konum: System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       konum: System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       konum: System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       konum: System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       konum: System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       konum: System.Windows.Forms.Application.RunDialog(Form form)
       konum: System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       konum: System.Windows.Forms.Form.ShowDialog()
       konum: tasarim.Form1.button1_Click(Object sender, EventArgs e) D:\Users\....\Documents\Visual Studio 2015\Projects\tasarim\tasarim\Form1.cs içinde: satır 36
       konum: System.Windows.Forms.Control.OnClick(EventArgs e)
       konum: System.Windows.Forms.Button.OnClick(EventArgs e)
       konum: System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       konum: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       konum: System.Windows.Forms.Control.WndProc(Message& m)
       konum: System.Windows.Forms.ButtonBase.WndProc(Message& m)
       konum: System.Windows.Forms.Button.WndProc(Message& m)
       konum: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       konum: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       konum: System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       konum: System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       konum: System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       konum: System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       konum: System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       konum: System.Windows.Forms.Application.Run(Form mainForm)
       konum: tasarim.Program.Main() D:\Users\....\Documents\Visual Studio 2015\Projects\tasarim\tasarim\Program.cs içinde: satır 19
       konum: System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       konum: System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       konum: Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       konum: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       konum: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       konum: System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```
